### ISSUE TITLE
python3 app.py 出错了

### ISSUE THREAD

**Issue by baitongda** [michaelliao/awesome-python3-webapp#34]
Traceback (most recent call last):
  File "app.py", line 154, in <module>
    loop.run_until_complete(init(loop))
  File "/usr/local/python3/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "app.py", line 142, in init
    yield from orm.create_pool(loop=loop, **configs.db)
  File "/home/wwwroot/LNMP/python_web/www/orm.py", line 20, in create_pool
    user=kw['awesome_user'],
KeyError: 'awesome_user'

**Comment by eduizhang** [comment]
是的，这个要怎么解决啊
